<?php

return [
        [
            'pickaxe',
            'dirt',
            5,
        ],
        [
            'pickaxe',
            'grass',
            5,
        ],
        [
            'pickaxe',
            'sand',
            5,
        ],
        [
            'pickaxe',
            'planks',
            5,
        ],
        [
            'pickaxe',
            'leaves',
            10,
        ],
        [
            'pickaxe',
            'fire',
            10,
        ],
        [
            'pickaxe',
            'wood',
            5,
        ],
        [
            'pickaxe',
            'glass',
            5,
        ],
        [
            'pickaxe',
            'stone',
            20,
        ],
        [
            'pickaxe',
            'iron',
            15,
        ],
        [
            'pickaxe',
            'chest',
            5,
        ],
        [
            'Axe',
            'dirt',
            5,
        ],
        [
            'Axe',
            'grass',
            5,
        ],
        [
            'Axe',
            'sand',
            5,
        ],
        [
            'Axe',
            'planks',
            12,
        ],
        [
            'Axe',
            'leaves',
            5,
        ],
        [
            'Axe',
            'Wood',
            12,
        ],
        [
            'Axe',
            'Glass',
            5,
        ],
        [
            'Axe',
            'stone',
            2,
        ],
        [
            'Axe',
            'iron',
            2,
        ],
        [
            'Axe',
            'chest',
            10,
        ],
        [
            'Shovel',
            'dirt',
            12,
        ],
        [
            'Shovel',
            'grass',
            12,
        ],
        [
            'Shovel',
            'sand',
            12,
        ],
        [
            'Shovel',
            'planks',
            3,
        ],
        [
            'Shovel',
            'leaves',
            5,
        ],
        [
            'Shovel',
            'wood',
            5,
        ],
        [
            'Shovel',
            'glass',
            20,
        ],
        [
            'Shovel',
            'stone',
            5,
        ],
        [
            'Shovel',
            'iron',
            5,
        ],
        [
            'Shovel',
            'coal',
            5,
        ],
        [
            'Shovel',
            'chest',
            5,
        ],
        [
            'stick',
            'water',
            10,
        ],
        [
            'stick',
            'fire',
            50,
        ],
        [
            'hand',
            'dirt',
            5,
        ],
        [
            'hand',
            'grass',
            5,
        ],
        [
            'hand',
            'sand',
            5,
        ],
        [
            'hand',
            'planks',
            5,
        ],
        [
            'hand',
            'leaves',
            5,
        ],
        [
            'hand',
            'fire',
            5,
        ],
        [
            'hand',
            'wood',
            5,
        ],
        [
            'hand',
            'glass',
            5,
        ],
        [
            'hand',
            'stone',
            5,
        ],
        [
            'hand',
            'iron',
            5,
        ],
        [
            'hand',
            'chest',
            5,
        ],
    ];
